import prod1 from "../../src/assets/products/prod1.png";
import prod2 from "../../src/assets/products/prod2.png";
import prod3 from "../../src/assets/products/prod3.png";
import prod4 from "../../src/assets/products/prod4.png";
import prod5 from "../../src/assets/products/prod5.png";
import prod6 from "../../src/assets/products/prod6.png";
import prod7 from "../../src/assets/products/prod7.png";
import prod8 from "../../src/assets/products/prod8.png";
import prod9 from "../../src/assets/products/prod9.png";
import prod from "../../src/assets/products/prod.png";
import product1 from "../../src/assets/products/product1.png";
import product2 from "../../src/assets/products/product2.png";
import product3 from "../../src/assets/products/product3.png";
import product4 from "../../src/assets/products/product4.png";
import product5 from "../../src/assets/products/porkleg.png";
import product6 from "../../src/assets/products/product6.png";
import product7 from "../../src/assets/products/product7.png";
import product8 from "../../src/assets/products/product8.png";
import product9 from "../../src/assets/products/product9.png";
import product from "../../src/assets/products/product.png";
import liver from "../../src/assets/products/liver.png";
import livestock from "../../src/assets/livestock/livestock.png";
import livestock1 from "../../src/assets/livestock/livestock1.png";
import livestock2 from "../../src/assets/livestock/livestock2.png";

import livestock4 from "../../src/assets/livestock/livestock4.png";

import PigFeed1 from "../../src/assets/livestock/PigFeed1.png";
import PigFeed2 from "../../src/assets/livestock/PigFeed2.png";
import PigFeed3 from "../../src/assets/livestock/PigFeed3.png";
import PigFeed4 from "../../src/assets/livestock/PigFeed4.png";
import PigFeed5 from "../../src/assets/livestock/PigFeed5.png";
import PigFeed6 from "../../src/assets/livestock/PigFeed6.png";
import PigFeed7 from "../../src/assets/livestock/PigFeed7.png";

export const orderStatement = [
  {
    id: "1",
    deliverydate: "12 Dec 2000",
    change: "2000",
    payout: "4000",
    price: "3000",
    product: {
      location: "Awka",
      name: "100% Healthy Pork Meat",
      weight: "1000g",
      productName: "100% Healthy Pork Lap",
    },
    img: prod2,
    status: "unpaid",
  },
  {
    id: "2",
    deliverydate: "2 Jan 2000",
    change: "1000",
    payout: "4000",
    price: "3000",
    product: {
      location: "Calabar",
      name: "100% Healthy Pork Lap",
      weight: "1000g",
      productName: "100% Healthy Pork Lap",
    },
    img: prod1,
    status: "unpaid",
  },
  {
    id: "3",
    deliverydate: "2 Jan 2000",

    change: "2300",
    payout: "2300",
    price: "3400",
    product: {
      location: "Calabar",
      name: "100% Healthy Pork Lap",
      weight: "1000g",
      productName: "100% Healthy Pork Lap",
    },

    img: prod3,
    status: "unpaid",
  },
  {
    id: "4",
    deliverydate: "3 Mar 1990",
    payout: "1000",
    price: "9400",
    product: {
      location: "Abuja",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },

    img: prod9,
    status: "unpaid",
  },
  {
    id: "5",
    deliverydate: "2 Mar 2003",
    payout: "1000",
    price: "5000",
    product: {
      location: "Awka",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    img: prod5,
    status: "unpaid",
  },

  {
    id: "6",
    deliverydate: "12 Jan 2020",
    payout: "4000",
    product: {
      location: "Awka",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "9200",
    img: prod6,
    status: "paid",
  },
  {
    id: "7",
    deliverydate: "1 Oct 2023",
    payout: "2300",
    product: {
      location: "Awka",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "1200",
    img: livestock,
    status: "paid",
  },
  {
    id: "8",
    deliverydate: "3 Apr 2024",
    payout: "2000",
    product: {
      location: "Awka",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "5000",
    img: prod8,
    status: "paid",
  },
  {
    id: "9",
    deliverydate: "7 Jun 2024",
    payout: "2000",
    product: {
      location: "Awka",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "5000",
    img: prod9,
    status: "paid",
  },
  {
    id: "10",
    deliverydate: "11 Oct 2022",
    payout: "2300",
    product: {
      location: "Calabar",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    img: livestock1,
    status: "paid",
  },
  {
    id: "11",
    deliverydate: "11 Oct 2022",
    payout: "2300",
    product: {
      location: "Benue",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    img: livestock2,
    status: "rejected",
  },
  {
    id: "12",
    deliverydate: "11 Oct 2022",
    payout: "2300",
    price: "2300",
    product: {
      location: "Benue",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    img: product2,
    status: "rejected",
  },
  {
    id: "13",
    deliverydate: "11 Oct 2022",
    payout: "2300",
    product: {
      location: "Benue",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    img: product3,
    status: "rejected",
  },
  {
    id: "14",
    deliverydate: "11 Oct 2022",
    payout: "4000",
    product: {
      location: "Benue",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    img: product4,
    status: "rejected",
  },
  {
    id: "15",
    deliverydate: "11 Oct 2022",
    payout: "4000",
    product: {
      location: "Benue",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    img: product5,
    status: "rejected",
  },
  {
    id: "16",
    deliverydate: "11 Oct 2022",
    payout: "4000",
    product: {
      location: "Benue",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    img: product6,
    status: "rejected",
  },
  {
    id: "17",
    deliverydate: "11 Oct 2022",
    payout: "4000",
    product: {
      location: "Benue",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    img: product7,
    status: "unpaid",
  },
  {
    id: "18",
    deliverydate: "11 Oct 2022",
    payout: "4000",
    product: {
      location: "Benue",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    img: product8,
    status: "unpaid",
  },
  {
    id: "19",
    deliverydate: "11 Oct 2022",
    payout: "4000",
    product: {
      location: "Benue",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    img: product9,
    status: "unpaid",
  },
  {
    id: "20",
    deliverydate: "11 Oct 2022",
    payout: "4000",
    product: {
      location: "Benue",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    img: product,
    status: "unpaid",
  },
  {
    id: "21",
    deliverydate: "12 Dec 2000",
    change: "2000",
    payout: "4000",
    price: "3000",
    product: {
      location: "Benue",
      name: "Cleaned Pork Liver",
      weight: "1000g",
      productName: "Cleaned Pork Liver",
    },
    img: liver,
    status: "rejected",
  },
  {
    id: "22",
    deliverydate: "2 Jan 2000",
    change: "2000",
    payout: "4000",
    price: "3000",
    product: {
      location: "Oyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    img: prod1,
    status: "rejected",
  },
  {
    id: "23",
    deliverydate: "2 Jan 2000",

    change: "4000",
    payout: "4000",
    price: "3400",
    product: {
      location: "Kaduna",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },

    img: prod2,
    status: "rejected",
  },
  {
    id: "24",
    deliverydate: "3 Mar 1990",
    payout: "1000",
    price: "9400",
    product: {
      location: "Abuja",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },

    img: prod3,
    status: "unpaid",
  },
  {
    id: "25",
    deliverydate: "2 Mar 2003",
    payout: "1000",
    price: "5000",
    product: {
      location: "Kaduna",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    img: prod4,
    status: "unpaid",
  },
  {
    id: "26",
    deliverydate: "6 Mar 2000",
    payout: "2300",
    product: {
      location: "Kaduna",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2000",
    img: prod5,
    status: "unpaid",
  },
  {
    id: "27",
    deliverydate: "12 Jan 2020",
    payout: "2000",
    product: {
      location: "Kaduna",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "9200",
    img: prod6,
    status: "unpaid",
  },
  {
    id: "28",
    deliverydate: "1 Oct 2023",
    payout: "1000",
    price: "1200",
    product: {
      location: "uyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    img: prod7,
    status: "unpaid",
  },

  {
    id: "31",
    deliverydate: "11 Oct 2022",
    payout: "1000",
    product: {
      location: "osun",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork ",
    },
    price: "2300",
    img: prod9,
    status: "unpaid",
  },
  {
    id: "32",
    deliverydate: "11 Oct 2022",
    payout: "1000",
    product: {
      location: "uyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    img: liver,
    status: "unpaid",
  },
  {
    id: "33",
    deliverydate: "11 Oct 2022",
    payout: "1000",
    product: {
      location: "uyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    img: prod,
    status: "unpaid",
  },
  {
    id: "34",
    deliverydate: "11 Oct 2022",
    payout: "1000",
    product: {
      location: "uyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    img: product,
    status: "unpaid",
  },
  {
    id: "35",
    deliverydate: "11 Oct 2022",
    payout: "1000",
    product: {
      location: "uyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    img: product1,
    status: "unpaid",
  },
  {
    id: "36",
    deliverydate: "11 Oct 2022",
    payout: "1000",
    product: {
      location: "uyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    img: prod1,
    status: "unpaid",
  },
  {
    id: "37",
    deliverydate: "11 Oct 2022",
    payout: "1000",
    price: "2300",
    product: {
      location: "uyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    img: prod2,
    status: "unpaid",
  },
  {
    id: "38",
    deliverydate: "11 Oct 2022",
    product: {
      location: "uyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    payout: "1000",
    price: "2300",
    img: prod4,
    status: "unpaid",
  },
  {
    id: "39",
    deliverydate: "11 Oct 2022",
    product: {
      location: "uyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    payout: "1000",
    price: "2300",
    img: prod2,
    status: "unpaid",
  },
  {
    id: "40",
    deliverydate: "11 Oct 2022",

    product: {
      location: "uyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    payout: "1000",
    price: "2300",
    img: livestock4,
    status: "unpaid",
  },
  {
    id: "41",
    deliverydate: "4 Mar 2023",
    payout: "1000",
    price: "2300",
    product: {
      location: "uyo",
      name: "pork Loin",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    img: prod3,
    status: "unpaid",
  },
  {
    id: "42",
    deliverydate: "5 Mar 2000",
    payout: "1000",
    product: {
      location: "uyo",
      name: "pork Loin",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    img: prod1,
    status: "unpaid",
  },
  {
    id: "43",
    deliverydate: "6 Mar 2014",
    payout: "1000",
    product: {
      location: "uyo",
      name: "pork Loin",
      productName: "100% Healthy-Fed Pork Lap",
    },

    price: "2300",
    img: prod1,
    status: "paid",
  },

  {
    id: "44",
    deliverydate: "11 Sept 2000",
    change: "2000",
    payout: "4000",
    price: "3000",
    product: {
      location: "Osun",
      name: "100% Healthy-Feed Pigs & Birds",
      weight: "1000g",
      productName: "100% Healthy-Feed Pigs ",
    },
    img: PigFeed1,
    status: "paid",
  },
  {
    id: "45",
    deliverydate: "5 Sept 2014",
    change: "5000",
    payout: "4000",
    price: "3000",
    product: {
      location: "Jos",
      name: "100% Healthy-Feed Pigs ",
      weight: "1000g",
      productName: "100% Healthy-Feed Pigs ",
    },
    img: PigFeed2,
    status: "paid",
  },
  {
    id: "46",
    deliverydate: "11 Sept 2000",
    change: "2000",
    payout: "4000",
    price: "3000",
    product: {
      location: "Anambra",
      name: "Whole Grain Mixed",
      weight: "1000g",
      productName: "Whole Grains for Pigs & Birds",
    },
    img: PigFeed3,
    status: "paid",
  },
  {
    id: "47",
    deliverydate: "11 Sept 2000",
    change: "2000",
    payout: "4000",
    price: "3000",
    product: {
      location: "Chikun City",
      name: " Gregory Whole Grain Mixed",
      weight: "1000g",
      productName: " Gregory Whole Grain Mixed",
    },
    img: PigFeed4,
    status: "paid",
  },
  {
    id: "48",
    deliverydate: "11 Sept 2000",
    change: "2000",
    payout: "4000",
    price: "3000",
    product: {
      location: "Kano",
      name: "Alhaji Grain for Birds",
      weight: "1000g",
      productName: "Alhaji Grain for Birds",
    },
    img: PigFeed5,
    status: "paid",
  },
  {
    id: "49",
    deliverydate: "11 Sept 2000",
    change: "2000",
    payout: "4000",
    price: "3000",
    product: {
      location: "Lagos",
      name: "Grace Grain for Birds",
      weight: "1000g",
      productName: "Grace Grain for Birds",
    },
    img: PigFeed6,
    status: "paid",
  },
  {
    id: "50",
    deliverydate: "11 Sept 2000",
    change: "2000",
    payout: "4000",
    price: "3000",
    product: {
      location: "Lagos",
      name: "Grace Grain for Birds",
      weight: "1000g",
      productName: "Grace Grain for Birds",
    },
    img: PigFeed7,
    status: "paid",
  },
];
