import prod1 from "../../src/assets/products/prod1.png";
import prod2 from "../../src/assets/products/prod2.png";
import prod3 from "../../src/assets/products/prod3.png";
import prod4 from "../../src/assets/products/prod4.png";
import prod5 from "../../src/assets/products/prod5.png";
import prod6 from "../../src/assets/products/prod6.png";
import prod7 from "../../src/assets/products/prod7.png";
import prod8 from "../../src/assets/products/prod8.png";
import prod9 from "../../src/assets/products/prod9.png";
import prod from "../../src/assets/products/prod.png";
import product1 from "../../src/assets/products/product1.png";
import product2 from "../../src/assets/products/product2.png";
import product3 from "../../src/assets/products/product3.png";
import product4 from "../../src/assets/products/product4.png";
import product5 from "../../src/assets/products/porkleg.png";
import product6 from "../../src/assets/products/product6.png";
import product7 from "../../src/assets/products/product7.png";
import product8 from "../../src/assets/products/product8.png";
import product9 from "../../src/assets/products/product9.png";
import product from "../../src/assets/products/product.png";
import liver from "../../src/assets/products/liver.png";
import livestock from "../../src/assets/livestock/livestock.png";
import livestock1 from "../../src/assets/livestock/livestock1.png";
import livestock2 from "../../src/assets/livestock/livestock2.png";
import livestock3 from "../../src/assets/livestock/livestock3.png";
import livestock4 from "../../src/assets/livestock/livestock4.png";
import livestock5 from "../../src/assets/livestock/livestock5.png";
import livestock6 from "../../src/assets/livestock/livestock6.png";
import PigFeed1 from "../../src/assets/livestock/PigFeed1.png";
import PigFeed2 from "../../src/assets/livestock/PigFeed2.png";
import PigFeed3 from "../../src/assets/livestock/PigFeed3.png";
import PigFeed4 from "../../src/assets/livestock/PigFeed4.png";
import PigFeed5 from "../../src/assets/livestock/PigFeed5.png";
import PigFeed6 from "../../src/assets/livestock/PigFeed6.png";
import PigFeed7 from "../../src/assets/livestock/PigFeed7.png";

export const productData = [
  {
    id: "1",
    title: "John Doe farm store",
    type: "Animal feed",
    category: "Feed",
    price: "3000",
    rating: "2.5",
    product: {
      location: "Awka",
      name: "100% Healthy Pork Meat",
      weight: "1000g",
      productName: "100% Healthy Pork Lap",
    },
    img: prod2,
    status: "Approved",
    desc: "A staple across Indian households, moong dal is widely used in a number of Indian delicacies. One such delicacy is moong dal cheela. ",
  },
  {
    id: "2",
    title: "Micheal bobo store",
    type: "Pork",
    category: "Feed",
    price: "3000",
    rating: "2.9",
    product: {
      location: "Calabar",
      name: "100% Healthy Pork Lap",
      weight: "1000g",
      productName: "100% Healthy Pork Lap",
    },
    img: prod1,
    status: "Approved",
    desc: "A staple across Indian households, moong dal is widely used in a number of Indian delicacies. One such delicacy is moong dal cheela.",
  },
  {
    id: "3",
    title: "Micheal bobo store",

    type: "Livestock",
    category: "Livestock",
    price: "3400",
    rating: "4.5",
    product: {
      location: "Calabar",
      name: "100% Healthy Pork Lap",
      weight: "1000g",
      productName: "100% Healthy Pork Lap",
    },

    img: prod3,
    status: "Approved",
    desc: "A staple across Indian households, moong dal is widely used in a number of Indian delicacies. One such delicacy is moong dal cheela. You can also add paneer to this recipe to amp up the nutritional value and make it, even more, protein-dense",
  },
  {
    id: "4",
    title: "Pig tail",
    category: "Pork",
    price: "9400",
    rating: "3.5",
    product: {
      location: "Abuja",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },

    img: prod9,
    status: "Approved",
    desc: "A classic dish that never goes out of style. The quintessential chana kulcha  needs only a few ingredients - cumin powder, ginger, coriander powder, carom powder, and some mango powder, which is what gives the chana its sour and tangy taste.",
  },
  {
    id: "5",
    title: "Pig Loin",
    category: "Pork",
    price: "5000",
    rating: "4.0",
    product: {
      location: "Awka",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    img: prod5,
    status: "Approved",
    desc: "Eggs are a versatile food that can be cooked for any meal of the day. From breakfast to dinner, it can be a go-to food. Here is a mildly-spiced egg curry made with garlic, onions, a whole lot of kasuri methi, fresh cream, yogurt, and fresh coriander.",
  },

  {
    id: "6",
    title: "Williams farm",
    category: "Feed",
    product: {
      location: "Awka",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "9200",
    rating: "3.5",
    img: prod6,
    status: "pending",
    desc: "Get your daily dose of perfect protein. Pieces of surmai fish marinated in garlic, cumin, fennel, curry leaves, and tomatoes are pan-fried in refined oil and served hot. This fish fry recipe has a host of delectable spices used for marination giving it a unique touch.",
  },
  {
    id: "7",
    title: "Dan pig farm",
    category: "Livestock",
    product: {
      location: "Awka",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "1200",
    rating: "2.55",
    img: livestock,
    status: "pending",
    desc: "Your family will thank you for this fantastic bowl of dum aloo cooked Lakhnawi style. Take some potatoes, crumbled paneer, kasuri methi, butter, onions, and some ghee.",
  },
  {
    id: "8",
    title: "Poultry farm",
    category: "Animal Feed",
    product: {
      location: "Awka",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "5000",
    rating: "4.9",
    img: prod8,
    status: "pending",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "9",
    title: "Poultry farm",
    category: "Animal Feed",
    product: {
      location: "Awka",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "5000",
    rating: "5.0",
    img: prod9,
    status: "pending",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "10",
    title: "pig Farm",
    category: "Livestock",
    product: {
      location: "Calabar",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    img: livestock1,
    status: "pending",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "11",
    title: "pig Farm",
    category: "Livestock",
    product: {
      location: "Benue",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    rating: "2.78",
    img: livestock2,
    status: "rejected",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "12",
    title: "pig Farm",
    category: "Livestock",
    price: "2300",
    rating: "2.5",
    product: {
      location: "Benue",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    img: product2,
    status: "rejected",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "13",
    title: "pig Farm",
    category: "Livestock",
    product: {
      location: "Benue",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    rating: "2.5",
    img: product3,
    status: "rejected",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "14",
    title: "pig Farm",
    category: "Livestock",
    product: {
      location: "Benue",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    rating: "1.5",
    img: product4,
    status: "rejected",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "15",
    title: "pig Farm",
    category: "Livestock",
    product: {
      location: "Benue",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    rating: "2.0",
    img: product5,
    status: "rejected",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "16",
    title: "pig Farm",
    category: "Livestock",
    product: {
      location: "Benue",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    rating: "3.58",
    img: product6,
    status: "rejected",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "17",
    title: "pig Farm",
    category: "Livestock",
    product: {
      location: "Benue",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    rating: "2.9",
    img: product7,
    status: "Approved",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "18",
    title: "pig Farm",
    category: "Livestock",
    product: {
      location: "Benue",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    rating: "2.5",
    img: product8,
    status: "Approved",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "19",
    title: "pig Farm",
    category: "Livestock",
    product: {
      location: "Benue",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    img: product9,
    rating: "2.5",
    status: "Approved",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "20",
    title: "pig Farm",
    category: "Livestock",
    product: {
      location: "Benue",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    rating: "2.5",
    img: product,
    status: "Approved",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "21",
    title: "John Doe farm store",
    type: "Animal feed",
    category: "Feed",
    price: "3000",
    rating: "2.90",
    product: {
      location: "Benue",
      name: "Cleaned Pork Liver",
      weight: "1000g",
      productName: "Cleaned Pork Liver",
    },
    img: liver,
    status: "rejected",
    desc: "gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes ",
  },
  {
    id: "22",
    title: "Micheal bobo store",
    type: "Animal feed",
    category: "Feed",
    price: "3000",
    rating: "2.5",
    product: {
      location: "Oyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    img: prod1,
    status: "rejected",
    desc: "gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes",
  },
  {
    id: "23",
    title: "Micheal bobo store",

    type: "Livestock",
    category: "Livestock",
    price: "3400",
    rating: "2.5",
    product: {
      location: "Kaduna",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },

    img: prod2,
    status: "rejected",
    desc: "A staple across Indian households, moong dal is widely used in a number of Indian delicacies. One such delicacy is moong dal cheela. You can also add paneer to this recipe to amp up the nutritional value and make it, even more, protein-dense",
  },
  {
    id: "24",
    title: "Pig tail",
    category: "Pork",
    price: "9400",
    rating: "2.5",
    product: {
      location: "Abuja",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },

    img: prod3,
    status: "approved",
    desc: "A classic dish that never goes out of style. The quintessential chana kulcha  needs only a few ingredients - cumin powder, ginger, coriander powder, carom powder, and some mango powder, which is what gives the chana its sour and tangy taste.",
  },
  {
    id: "25",
    title: "Pig Loin",
    category: "Pork",
    price: "5000",
    rating: "2.5",
    product: {
      location: "Kaduna",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    img: prod4,
    status: "approved",
    desc: "Eggs are a versatile food that can be cooked for any meal of the day. From breakfast to dinner, it can be a go-to food. Here is a mildly-spiced egg curry made with garlic, onions, a whole lot of kasuri methi, fresh cream, yogurt, and fresh coriander.",
  },
  {
    id: "26",
    title: "Dangotes farm",
    category: "Livestock",
    product: {
      location: "Kaduna",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2000",
    rating: "2.5",
    img: prod5,
    status: "approved",
    desc: "Don't get intimidated by the list of ingredients because not only are already in your kitchen cabinet, but also because all they'll need is 20 minutes of your time. Chunks of cottage cheese cooked in some exciting spices, yogurt and a pinch of sugar.",
  },
  {
    id: "27",
    title: "Williams farm",
    category: "Animal Feed",
    product: {
      location: "Kaduna",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "9200",
    rating: "2.5",
    img: prod6,
    status: "approved",
    desc: "Get your daily dose of perfect protein. Pieces of surmai fish marinated in garlic, cumin, fennel, curry leaves, and tomatoes are pan-fried in refined oil and served hot. This fish fry recipe has a host of delectable spices used for marination giving it a unique touch.",
  },
  {
    id: "28",
    title: "Dan pig farm",
    category: "Pork",
    price: "1200",
    rating: "2.5",
    product: {
      location: "uyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    img: prod7,
    status: "approved",
    desc: "Your family will thank you for this fantastic bowl of dum aloo cooked Lakhnawi style. Take some potatoes, crumbled paneer, kasuri methi, butter, onions, and some ghee.",
  },
  {
    id: "29",
    title: "Poultry farm",
    category: "Animal Feed",
    price: "5000",
    rating: "2.5",
    img: "./images/productimg2.png",
    status: "approved",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "30",
    title: "pig Farm",
    category: "Pork",
    price: "2300",
    rating: "2.5",
    img: prod8,
    status: "approved",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "31",
    title: "pig Farm",
    category: "Pork",
    rating: "2.5",
    product: {
      location: "osun",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork ",
    },
    price: "2300",
    img: prod9,
    status: "approved",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "32",
    title: "pig Farm",
    category: "Pork",
    product: {
      location: "uyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    rating: "2.5",
    img: liver,
    status: "approved",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "33",
    title: "pig Farm",
    category: "Pork",
    product: {
      location: "uyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    rating: "2.5",
    img: prod,
    status: "approved",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "34",
    title: "pig Farm",
    category: "Pork",
    product: {
      location: "uyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    rating: "2.5",
    img: product,
    status: "approved",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "35",
    title: "pig Farm",
    category: "Pork",
    product: {
      location: "uyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    rating: "2.5",
    img: product1,
    status: "approved",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "36",
    title: "pig Farm",
    category: "Pork",
    product: {
      location: "uyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    rating: "2.5",
    img: prod1,
    status: "approved",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "37",
    title: "pig Farm",
    category: "Pork",
    price: "2300",
    rating: "2.5",
    product: {
      location: "uyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    img: prod2,
    status: "approved",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "38",
    title: "pig Farm",
    product: {
      location: "uyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    category: "Pork",
    price: "2300",
    rating: "2.5",
    img: prod4,
    status: "approved",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "39",
    title: "pig Farm",
    product: {
      location: "uyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    category: "Pork",
    price: "2300",
    rating: "2.5",
    img: prod2,
    status: "approved",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "40",
    title: "pig Farm",

    product: {
      location: "uyo",
      name: "100% Healthy-Fed Pork Lap",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    category: "Pork",
    price: "2300",
    rating: "2.5",
    img: livestock4,
    status: "approved",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "41",
    title: "test Farm",
    category: "Pork",
    price: "2300",
    rating: "2.5",
    product: {
      location: "uyo",
      name: "pork Loin",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    img: prod3,
    status: "approved",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "42",
    title: "test test",
    category: "Pork",
    product: {
      location: "uyo",
      name: "pork Loin",
      weight: "1000g",
      productName: "100% Healthy-Fed Pork Lap",
    },
    price: "2300",
    rating: "2.5",
    img: prod1,
    status: "approved",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "43",
    title: "Data Farm",
    category: "Pork",
    product: {
      location: "uyo",
      name: "pork Loin",
      productName: "100% Healthy-Fed Pork Lap",
    },

    price: "2300",
    rating: "2.5",
    img: prod1,
    status: "pending",
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },

  {
    id: "44",
    title: "Dantata Feed Store",
    type: "Animal feed",
    category: "Feed",
    price: "3000",
    rating: "2.5",
    product: {
      location: "Osun",
      name: "100% Healthy-Feed Pigs & Birds",
      weight: "1000g",
      productName: "100% Healthy-Feed Pigs ",
    },
    img: PigFeed1,
    status: "pending",
    desc: "A staple across Indian households, moong dal is widely used in a number of Indian delicacies. One such delicacy is moong dal cheela. ",
  },
  {
    id: "45",
    title: "Khadijat Feed Store",
    type: " Feed",
    category: "Feed",
    price: "3000",
    rating: "2.5",
    product: {
      location: "Jos",
      name: "100% Healthy-Feed Pigs ",
      weight: "1000g",
      productName: "100% Healthy-Feed Pigs ",
    },
    img: PigFeed2,
    status: "pending",
    desc: "A staple across Indian households, moong dal is widely used in a number of Indian delicacies. One such delicacy is moong dal cheela. ",
  },
  {
    id: "46",
    title: "Dantata Feed Store",
    type: "Animal feed",
    category: "Feed",
    price: "3000",
    rating: "2.5",
    product: {
      location: "Anambra",
      name: "Whole Grain Mixed",
      weight: "1000g",
      productName: "Whole Grains for Pigs & Birds",
    },
    img: PigFeed3,
    status: "pending",
    desc: "A staple across Indian households, moong dal is widely used in a number of Indian delicacies. One such delicacy is moong dal cheela. ",
  },
  {
    id: "47",
    title: "Nkeke Feed Store",
    type: "Animal feed",
    category: "Feed",
    price: "3000",
    rating: "2.5",
    product: {
      location: "Chikun City",
      name: " Gregory Whole Grain Mixed",
      weight: "1000g",
      productName: " Gregory Whole Grain Mixed",
    },
    img: PigFeed4,
    status: "pending",
    desc: "A staple across Indian households, moong dal is widely used in a number of Indian delicacies. One such delicacy is moong dal cheela. ",
  },
  {
    id: "48",
    title: "Jumbo Feed Store Ltd.",
    type: "Animal feed",
    category: "Feed",
    price: "3000",
    rating: "2.5",
    product: {
      location: "Kano",
      name: "Alhaji Grain for Birds",
      weight: "1000g",
      productName: "Alhaji Grain for Birds",
    },
    img: PigFeed5,
    status: "pending",
    desc: "A staple across Indian households, moong dal is widely used in a number of Indian delicacies. One such delicacy is moong dal cheela. ",
  },
  {
    id: "49",
    title: "Madam Grace Grains",
    type: "Animal feed",
    category: "Feed",
    price: "3000",
    rating: "2.5",
    product: {
      location: "Lagos",
      name: "Grace Grain for Birds",
      weight: "1000g",
      productName: "Grace Grain for Birds",
    },
    img: PigFeed6,
    status: "pending",
    desc: "A staple across Indian households, moong dal is widely used in a number of Indian delicacies. One such delicacy is moong dal cheela. ",
  },
  {
    id: "50",
    title: "Madam Grace Grains",
    type: "Animal feed",
    category: "Feed",
    price: "3000",
    rating: "2.5",
    product: {
      location: "Lagos",
      name: "Grace Grain for Birds",
      weight: "1000g",
      productName: "Grace Grain for Birds",
    },
    img: PigFeed7,
    status: "pending",
    desc: "A staple across Indian households, moong dal is widely used in a number of Indian delicacies. One such delicacy is moong dal cheela. ",
  },
];

export const bestSelling = [
  {
    id: "1",
    title: "John Doe farm store",
    category: "Animal Feed",
    price: "3000",
    location: "Lagos",
    img: prod1,

    desc: "100%  Healthy-Fed Pork Lap ",
  },
  {
    id: "2",
    title: "Micheal bobo store",
    category: "Animal Feed",
    price: "3000",
    location: "Ogun",
    img: prod9,
    desc: "100%  Healthy-Groundnut",
  },
  {
    id: "3",
    title: "Micheal bobo store",
    category: "Livestock",
    price: "2300",
    location: "Abuja",
    img: prod8,
    desc: "A staple across Indian households, moong dal is widely used in a number of Indian delicacies. One such delicacy is moong dal cheela. You can also add paneer to this recipe to amp up the nutritional value and make it, even more, protein-dense",
  },
  {
    id: "4",
    title: "Pig Head",
    category: "Pig",
    price: "6000",
    location: "Akwa_Ibom",
    img: prod7,
    desc: "A classic dish that never goes out of style. The quintessential chana kulcha  needs only a few ingredients - cumin powder, ginger, coriander powder, carom powder, and some mango powder, which is what gives the chana its sour and tangy taste.",
  },
  {
    id: "5",
    title: "Pig Loin",
    category: "Pig",
    price: "5000",
    location: "Kano",
    img: livestock3,
    desc: "Eggs are a versatile food that can be cooked for any meal of the day. From breakfast to dinner, it can be a go-to food. Here is a mildly-spiced egg curry made with garlic, onions, a whole lot of kasuri methi, fresh cream, yogurt, and fresh coriander.",
  },
  {
    id: "6",
    title: "Dangotes farm",
    category: "Livestock",
    price: "2000",
    location: "Lagos",
    img: prod5,
    desc: "Don't get intimidated by the list of ingredients because not only are already in your kitchen cabinet, but also because all they'll need is 20 minutes of your time. Chunks of cottage cheese cooked in some exciting spices, yogurt and a pinch of sugar.",
  },
  {
    id: "7",
    title: "Williams farm",
    category: "Animal Feed",
    price: "9200",
    location: "Lagos",
    img: prod4,
    desc: "Get your daily dose of perfect protein. Pieces of surmai fish marinated in garlic, cumin, fennel, curry leaves, and tomatoes are pan-fried in refined oil and served hot. This fish fry recipe has a host of delectable spices used for marination giving it a unique touch.",
  },
  {
    id: "8",
    title: "Dan pig farm",
    category: "Pig",
    price: "1200",
    location: "Ogun",
    img: prod3,
    desc: "Your family will thank you for this fantastic bowl of dum aloo cooked Lakhnawi style. Take some potatoes, crumbled paneer, kasuri methi, butter, onions, and some ghee.",
  },
  {
    id: "9",
    title: "Poultry farm",
    category: "Animal Feed",
    price: "5000",
    location: "Lagos",
    img: prod2,
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
  {
    id: "10",
    title: "pig Farm",
    category: "Pig",
    location: "Calabar",
    price: "2300",
    img: prod1,
    desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
  },
];
